### ISSUE TITLE
How to prevent users from accidentally forgetting to implement a custom type function?

### ISSUE THREAD

**Issue by josdejong** [ericman314/UnitMath#16]
The library looks really great already :+1: 

After reading #15, I was thinking: there are about 10 functions that you have to implement to support a custom type like bignumbers. If I'm not mistaken, the library will not warn you when you have forgotten to implement some of them. This may give unexpected behavior that could cause loss of precision for example. 

How about either forcing to implement all of the functions, or throwing a warning when using a custom type function that is not overridden whilst others are?

**Comment by ericman314** [comment]
Thanks!

I had the same thought. I will definitely add warnings or errors where appropriate.

**Comment by josdejong** [comment]
:+1:

**Comment by ericman314** [comment]
This was resolved since v0.4.0
