### ISSUE TITLE
Make all units immutable

### ISSUE THREAD

**Issue by harrysarson** [ericman314/unitmath#2]
### Related to #1 - an idea I would like to throw out:

The API will be cleaner, bugs harder to introduce and maintenance a _lot_ less of a burden if every type defined in unitmath is immutable*.

The major downside would be a possible performance cost but I would argue against any premature optimisations without benchmarks that show cloning units is a bottleneck.

---

Related: when configuring the global options, any changes made in one file should be independent from changes made in other files. Currently

```js
unit.config(options)
```

updates the global unit configuration. A better API might be 

```js
newUnit = oldUnit.config(options)
```

where the `config()` function returns a brand new instance.

---

*: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze#Browser_compatibility

**Comment by ericman314** [comment]
Thanks for your ideas, @harrysarson!

> every type defined in unitmath is immutable

I absolutely agree. Good idea to use `Object.freeze()`, I hadn't thought of that. All of the public API functions will return a new, frozen unit.

> the `config()` function returns a brand new instance

What exactly do you mean by that? Do you mean that the factory function `unit` and its configurable options would be cloned? So you would do:

```js
const unit = require('unitmath')

const newUnit = unit.config(options)

// Use newUnit factory to build units
newUnit('3 kg')  // and so on
```

Then you could also do:

```js
const unit = require('unitmath').config(options)
```

Is that what you had in mind?

**Comment by harrysarson** [comment]
Yes, exactly what I have in mind!

**Comment by ericman314** [comment]
I've updated the README with your suggestions, thanks again!

**Comment by harrysarson** [comment]
Looks perfect!
