### ISSUE TITLE
What happens when adding units with different numerical types?

### ISSUE THREAD

**Issue by harrysarson** [ericman314/UnitMath#3]
We have proposed allowing unitmath to be extended with custom numeric types by defining `add`, `multiply` etc in the config.

What happens if a user defines a unit based on a custom numeric type and tries to add a unit based on `Number`s to it? What happens when a user tries to add two units based on different custom numeric types?

**Comment by ericman314** [comment]
UnitMath is totally blind to the inner workings of the user's custom functions, and will happily work with any type (except `string`) the user gives it. I think that is an important point. So I suppose the user will be required to perform their own type checking, and handle all of the different cases in their own functions. Math.js already does this using `typed-function`, so I think it would be easy to make it work in that case.

**Comment by harrysarson** [comment]
Makes sense 👍

**Comment by harrysarson** [comment]
This could mean that

```js
unit1.add(unit2) !== unit2.add(unit1)
```

as the left hand side would be evaluated by the `customAdd` function of `unit1` and the right hand side would be evaluated by the `customAdd` function of `unit2`. This may not be a problem but it does violate the commutativity of addition.

**Comment by ericman314** [comment]
Great observation. I'm not sure what to do about that. It does seem to be a strange use case to define and use two different custom functions at the same time. Perhaps, like JavaScript, there will be some anti-patterns that are possible but not great ideas. Maybe a few examples of these anti-patterns in the readme would help?

There are definitely ways UnitMath could check for potential problems like this, such as any binary operation with units constructed from different namespaces, or only overriding some, but not all, of the custom arithmetic functions. Would a `console.warn` message be appropriate in this case? A user could turn off the checking to improve performance.

**Comment by harrysarson** [comment]
I have been thinking more about this and I think there are two types of configuration: formatting and arithmetic.

Formatting options only effect the function `format()` and a unit's formatting configuration _could_* change without invalidating. These options have no effect on the value of unit - only the conversion to string. 

To change the arithmetic options for an existing unit would not make sense as the value of a unit depends on the behaviour of the arithmetic operations used to to create it.

Binary options with units with different formatting options make sense and I think we can decide upon a way of choosing the options used in the result. However, binary arithmetic operation on two units with different arithmetic configuration either require a special behaviour or should fail. 

---

*: The configuration can't change as units are immutable.

**Comment by harrysarson** [comment]
Perhaps what I am suggesting is to replace the flat configuration object with something like:

![image](https://user-images.githubusercontent.com/16308754/57301683-80081580-70d1-11e9-856c-fba82da31659.png)

**Comment by ericman314** [comment]
Yeah, the number of config options is great enough now that it might make sense to separate them like how you have proposed. I do think it would be acceptable to pass the format portion of the config to `format()` or `toString()` to change the formatting that one time. I also would like to make the config a place for custom units, but I'll continue that discussion in a separate issue.

**Comment by ericman314** [comment]
I've put a small example of extending types in the `examples/` folder. Amazingly, it works!

https://github.com/ericman314/UnitMath/blob/master/examples/decimal.js

**Comment by harrysarson** [comment]
I had a look at the interaction between normal units and Decimal units here: https://runkit.com/harrysarson/unitmath-3.

Strange is that one can do ` big_unit(unit('3 m'))` without an error but then it throws when converting to string.

**Comment by josdejong** [comment]
Really cool and powerful :sunglasses:
