### ISSUE TITLE
API is getting too complicated and it's not even at v1.0 yet

### ISSUE THREAD

**Issue by ericman314** [ericman314/UnitMath#34]
I think part of the reason development has stalled, is the API is getting too complicated. The "auto add to unit system" feature, which is needed by mathjs, is what pushed me over the edge. As an experiment, I am starting a new branch where I am stripping out base quantities, quantities, and unit systems, and keeping only the units and prefixes--and see how many of the features I can retain with these simplifications. @josdejong, someday I hope it can be integrated into math.js.

**Comment by ericman314** [comment]
I removed the unit systems, quantities, and explicit base quantities from the definitions. (Base quantities are still defined implicitly in the definitions of the base units, for example, `meter: {quantity: "LENGTH", value: 1}`.)  In addition, I refactored Unit.dimension to be an object with the base quantities as properties of that object, rather than an array with fixed indices. This actually simplifies the code in the multiply and divide functions a little bit, which is a pleasant surprise. The library is agnostic about what base dimensions you use in the unit definitions. Any specification of a `quantity` in a unit definition creates a base quantity.

The `simplify` function is completely broken now, as a result of removing the unit systems. I added a stop-gap simplify method that just formats a unit using the base units (the ones that use a `quantity` in their definition.) Luckily, many of the tests are still passing, except for the ones involving simplify.

We will have to bring the unit systems back eventually in order to make simplify work, otherwise the library would just pick matching units at random to do simplification. For an explicit unit system like "SI" or "US", it shouldn't be too hard to just mark some of the units as belonging to those systems, and then simplify will prefer to use those units during formatting.

The "auto" unit system is where things start to get tricky. We've got to somehow infer which units are most closely related to others. Perhaps, units derived from other units can inherit the unit system from those units they derive from, if the system isn't explicitly given in the derived unit's definition. Then when those derived units are encountered, we perform the calculation, look at the resulting units, select the most common unit system, and select the base unit or derived unit that most closely matches.

I think what will be key here is to reduce the amount of "configuration" the user has to do. So, rather than explicitly giving a `unitSystems` object with a million things in it, just specify `system: "si"` on each of the SI base units, `system: "us"` on some of the us units, and the inheritance model should take care of the rest. Or perhaps, some kind of "distance" metric defined as the number of edges between a proposed unit and the constituent units, along the inheritance tree.

**Comment by josdejong** [comment]
A fresh take on it sounds good! Great to see you're working on this again 😎 

Just to be sure we're on the same page: please _first_ make the best unit library you can imagine, and only _second_ see how we can integrate this in mathjs. We should not be afraid for breaking changes in mathjs (as long as they are for the better ;) ), though we should try to minimize this of course. I expect we'll need some extra code in mathjs to get UnitMath nicely integrated there, but ideally UnitMath should not become sub-obtimal due to mathjs limitations.

Indeed the "auto" unit system is complex. Would it be possible to somehow let `auto` follow a set of configurable rules, so the behavior is clearly defined and the user can change and tweak these rules to their own taste?

**Comment by ericman314** [comment]
See below the proposed api for the new systems definition. It's much simpler than anything else we've tried.

**definitions.systems**

This object assigns one or more units to a number of systems. Each key in `definitions.systems` becomes a system. Each system lists all the units that should be associated with that system in an array. The units may include prefixes.

```js
systems: {
  si: ['m', 'kg', 's', 'N', 'J'],
  cgs: ['cm', 'g', 's', 'dyn', 'erg'],
  us: ['ft', 'lbm', 's', 'lbf', 'btu']
}
```

When UnitMath formats a unit, it will try to use one of the units from the specified system first. If no matching unit in that system exists, it will choose from all available units.

**Comment by josdejong** [comment]
That makes a lot of sense! It looks very simple. Would UnitMath understand that when specifying `us: ['ft', ...]`, all length related units should be output in feet related units (feet, inch, ...)?

**Comment by ericman314** [comment]
Unfortunately, right now only units that are included in the `systems` array are recognized as belonging to that system. So feet, ft, inch, in, and all the others each need to be included in the array. I'm trying to think about ways that it could infer which units belong to the system without explicitly including all of them. But for now, including all of them works.

**Comment by josdejong** [comment]
It should not be too hard to create groups of units like 

```js
const imperialLengthUnits = ['feet', 'ft', 'inch', 'in']
```

and then add them all at once:

```
systems: {
  si: ['m', 'kg', 's', 'N', 'J'],
  cgs: ['cm', 'g', 's', 'dyn', 'erg'],
  us: [...imperialLengthUnits, 'lbm', 's', 'lbf', 'btu']
}
```

I'm not sure though if this is easy to maintain when adding new units. Maybe the units could have a "groups" property or so.

Just thinking aloud here...

**Comment by hibachi2021** [comment]
@ericman314 Great job on building up UnitMath! I particularly like how it can (I think?) allow a custom Object (e.g., via JSON) to essentially be loaded into UnitMath to provide custom definitions to use (i.e., `.config()` method). My apologies for any misunderstandings as I am exploring various 'unit handling' libraries and just started looking at UnitMath, but thought I'd comment on some of the discussion from above.

If I understand your newly proposed systems structure, for any given unit in the array, can you just use the `quantity` value defined for the unit to filter on all "related" units? e.g., 'feet', 'inch', 'yard', 'meter', 'mile', ..., while the `aliases` array for each of these related units would then provide the other variations, e.g., 'ft', 'in', 'inches', 'yd', 'm', 'mi',  ...?

On another note:
One of the things that I am wondering about is whether there will no longer be a way to organize certain base quantity combinations as quantities. e.g., SPEED = [LENGTH / TIME] or THERMAL CONDUCTIVITY = [POWER / LENGTH TEMPERATURE]
This would be particularly useful when trying to search for related derived quantities.

If I understood the above, derived units will have autogenerated `quantity` values based on the unit value definition? 
e.g., `"mph": "1 mi / hr"` would automatically have generated `"quantity": "LENGTH / TIME"`

For simple derived units like speed, this may be ok, but if a user wanted to find `compatible units` for e.g., Power, they will first need to decompose to base quantities then search on this? i.e., `MASS LENGTH^2 TIME^-3`

In addition, one of the challenges with searching on decomposed base dimensions/quantities is that some physical quantities have the same derived base dimensions but are typically described using different unit combinations. e.g., Energy Density [ENERGY / VOLUME] (e.g., J/m3) vs. Pressure [FORCE / AREA] (Pa), both of which decompose to [MASS / LENGTH TIME^2]

All that to ask whether derived quantity labeling like SPEED, POWER, AREA, etc. will no longer be possible. Thanks!

**Comment by ericman314** [comment]
Thank you for your kind remarks and insightful comments! Due to a variety of circumstances I cannot spend much time on UnitMath right now but I do hope to get v1 finished eventually.

## The Short Answer ##
Determining the quantities `SPEED`, `POWER`, `AREA`, will still be possible manually, just with a little more effort. By design, it won't initially be a built-in feature of the library, but it would definitely be useful to add later on. 

## The Long Answer ##

**Aliases:** This is just a shortcut so you don't have to repeat the definition for all variations like `ft`, `feet`, `foot`. Internally, it just clones the definition for each alias.


**Querying quantities:** I do not think it will be possible to "filter on all related units" using the `quantity` value. Defining this value tells the API to create a new *base unit*, like length or time. So when defining a unit such as `mph`, there will not be a `quantity` field. Instead of `quantity: 'SPEED'`, it will have the property `dimension: { LENGTH: 1, TIME: -1 }`, which it determines from the definition: `"mph": "1 mi / hr"`.

Having a `quantity` property for each unit was very appealing but I realized it was probably unnecessary. This is because there is already an `equalsQuantity` method that compares the quantity of one unit with another, by comparing their `dimension` objects. In theory you could create your own reference object of units to compare against:

```js
const refQuantities = {
  MASS: 'kg',
  SPEED: 'm/s',
  ...
];

let myUnit = unit('4 mile/hour');
myUnit.equalsQuantity(refQuantities.SPEED); // true
```

I realize it's not quite as convenient as writing `myUnit.quantity`, but I really want to slim down the library to only the essential parts. I wanted to make it super easy to define your own units without requiring tons of boilerplate definitions. Perhaps eventually we could add a built-in feature to spit out `"SPEED"` automatically, but **I don't want the inner workings of the library to be dependent on this feature**, as it would require users to specify these quantities for each custom unit they add. (We could also add a `getMatchingUnits` method which returns an array of all the defined units which match the given unit. This could be used to populate a drop-down selector for a unit conversion tool, for example.)

**Energy Density vs. Pressure:** That's a really interesting example! The fact that those are the same units gives a lot of physical insight. For instance, this relationship is seen in the concept of "flow work" in the energy balance of an open system: https://youtu.be/rWuikkYEFBE?t=45. Or in the calculation of work required to compress a gas.

Another example of two quantities that have the same dimensions are energy and torque. I'm not sure how the library could distinguish between two values which have the same units but different meanings. There's no way for it to follow a set of calculations and infer the physical meaning of an expression. I think that problem is universal in computing: somewhere you need a human to interpret the results.

**Comment by ericman314** [comment]
Closing; please see #45

**Comment by TheOneTheOnlyJJ** [comment]
> **Querying quantities:** I do not think it will be possible to "filter on all related units" using the `quantity` value. Defining this value tells the API to create a new _base unit_, like length or time. So when defining a unit such as `mph`, there will not be a `quantity` field. Instead of `quantity: 'SPEED'`, it will have the property `dimension: { LENGTH: 1, TIME: -1 }`, which it determines from the definition: `"mph": "1 mi / hr"`.
> 
> Having a `quantity` property for each unit was very appealing but I realized it was probably unnecessary. This is because there is already an `equalsQuantity` method that compares the quantity of one unit with another, by comparing their `dimension` objects. In theory you could create your own reference object of units to compare against:
> 
> ```js
> const refQuantities = {
>   MASS: 'kg',
>   SPEED: 'm/s',
>   ...
> ];
> 
> let myUnit = unit('4 mile/hour');
> myUnit.equalsQuantity(refQuantities.SPEED); // true
> ```
> 
> I realize it's not quite as convenient as writing `myUnit.quantity`, but I really want to slim down the library to only the essential parts. I wanted to make it super easy to define your own units without requiring tons of boilerplate definitions. Perhaps eventually we could add a built-in feature to spit out `"SPEED"` automatically, but **I don't want the inner workings of the library to be dependent on this feature**, as it would require users to specify these quantities for each custom unit they add. (We could also add a `getMatchingUnits` method which returns an array of all the defined units which match the given unit. This could be used to populate a drop-down selector for a unit conversion tool, for example.)


Now that v1.0 is long released, would it be feasible to implement the mentioned `getMatchinUnits` method? It would make developing front end unit manipulation components a lot easier.
For example, I want to have a data grid column populated with units of a specific quantity, and allow the end user to select in which units to display the values based on a selection made in the column header through a custom component that would have a dropdown menu containing the valid matching units for the given quantity. The `getMatchingUnits` method would be of great help here.

It would also be useful for the library to provide a default `refQuantities` object, populated with the most common physical quantities, such as the mentioned `"MASS"`, `"SPEED"`, but also uncompounded powers of base quantities such as `"AREA"` and `"VOLUME"`. The user could of course define their own object for any custom quantities.
