### ISSUE TITLE
TypeScript?

### ISSUE THREAD

**Issue by m93a** [ericman314/UnitMath#36]
Do you consider providing TypeScript definitions for the API? Or, better, porting the source code to TypeScript entirely? I consider using this package in a repository where type safety is crucial, so this would be a welcome addition for me.

If you *do* consider any of these two things, I'll be hapy to help with that in any way I can :)

**Comment by ericman314** [comment]
Oh, yeah, that would be really cool! I'm in the middle of a big refactoring right now, and the API _will_ change before we get to v1.0. The branch I'm actively working on now, and which I hope can become v1.0, is `make-things-less-complicated`.

I've only added typescript definitions to one other project before, and I've never written source code using typescript, but it's something I've been wanting to try.

**Comment by ericman314** [comment]
Closing; please see #45
