### ISSUE TITLE
Simplify the API of the formatter

### ISSUE THREAD

**Issue by josdejong** [ericman314/UnitMath#47]
Looking at the docs of the custom formatter, https://github.com/ericman314/UnitMath#custom-formatter , I have the feeling that the `formatter` option can be simpler, by removing the possibility to pass additional arguments to it via toString. I think you can achieve that already by changing:

```js
unit('3.14159 rad').toString({ formatter: funnyFormatter }, '$', '_'
```

to

```js
unit('3.14159 rad').toString({ formatter: value => funnyFormatter(value, '$', '_') }

// or 

const funnyFormatter$ = value => funnyFormatter(value, '$', '_')
unit('3.14159 rad').toString({ formatter: funnyFormatter }
```

**Comment by ericman314** [comment]
I'm not sure. I definitely agree that the documentation on `formatter` is too complicated though. I don't remember if there was a reason we had to support passing user args into the formatter. Maybe when I wrote it I had just learned about JavaScript's spread operator and was looking for a nail to hit with that hammer. I would be okay removing it.

**Comment by josdejong** [comment]
👍  not a big deal, I just felt like the API could be a _bit_ simpler without sacrificing anything.

**Comment by ericman314** [comment]
I ended up taking your advice in 1.0.0-rc2 and removed the additional arguments to the custom formatter, under the principle of "you aren't gonna need it."

**Comment by josdejong** [comment]
👍
