### ISSUE TITLE
Typescript Support for users of the library

### ISSUE THREAD

**Issue by JGantner** [ericman314/UnitMath#55]
I'm using this awesome library in a larger TS project and it would be awesome to somehow have types for the objects returned by the library. I'm on an older version right now but the version 1.0.0 seems to not export any type information. 
I saw that you started to adopt TS for the development of the library. Are there plans to somehow export types for users of this library? I'm no sure if i understand the code enough, but would you be interested in a Pull Request?

**Comment by ericman314** [comment]
Oh yes, we definitely want to export types. I could take a look at it in the next few weeks, but if you already know what needs to be done I would be very happy to take a pull request.

**Comment by JGantner** [comment]
To be honest if have no clue what is needed but i'll try to figure something out.

**Comment by ericman314** [comment]
I published v1.0.1, which correctly (I think?) exports the types. Do you mind giving that a try?

```js
import unit from "unitmath";

let u = unit('10 m') // Unit<number>
```

**Comment by JGantner** [comment]
Just tried it in my small test app and it seems to work great. I'll try to update it in our bigger app and see if it works there as intended.
Thanks for the update.

**Comment by JGantner** [comment]
At a first glance it also works on our bigger project. But i now have wo fix ~130 type issues. Thanks, i also discovered some issues that may lead to unintended consequences. That was what i was hoping for.

**Comment by ericman314** [comment]
That's great! Let me know if I can be of any more help...
