### ISSUE TITLE
Bundling

### ISSUE THREAD

**Issue by harrysarson** [ericman314/UnitMath#8]
What files do you plan to include in the published version? I have thought of the following:

1. An module entry point - pointed to by the `"module"` field in `package.json`.
2. A node entry point - pointed to by the `"main"` field in `package.json`.
3. A bundled es module for use in very new browsers.
4. A bundled UMD file for use in browsers that are no IE 11.
5. A bundled UMD that has been run through babel for IE 11.

**Comment by ericman314** [comment]
I wasn't entirely sure about that. Whatever you think is best!

**Comment by harrysarson** [comment]
https://unpkg.com/unitmath@0.0.1/: the built files have not made in into the npm package alas!

**Comment by ericman314** [comment]
Aha, I guess `npm run build` is important.

https://unpkg.com/unitmath@0.1.1/

**Comment by ericman314** [comment]
I think I have resolved this via https://github.com/ericman314/UnitMath/commit/1ce6e38ee05b2dbbc00398c4efc33ee7df103059.
